services:
  - type: web
    name: devflix-api
    runtime: php
    plan: free
    repo: https://github.com/DaniloPy-coder/Devflix
    rootDir: back-end
    buildCommand: "composer install --no-dev --optimize-autoloader && php artisan migrate --force" 
    startCommand: "php -S 0.0.0.0:$PORT -t public"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generate: true